#file will have the list of dictionaries for each company
#will be used to populate the database once all data is collected

companies = [
    {"company_name": "Cognizant Technology Solutions", "job_scope": {}},
    {"company_name": "Infosys", "job_scope": {}},
    {"company_name": "Tata Consultancy Services", "job_scope": {}},
    {"company_name": "Google", "job_scope": {}},
    {"company_name": "Ernst & Young", "job_scope": {}},
    {"company_name": "Capgemini", "job_scope": {}},
    {"company_name": "Deloitte & Touche", "job_scope": {}},
    {"company_name": "Amazon", "job_scope": {}},
    {"company_name": "IBM", "job_scope": {}},
    {"company_name": "Microsoft", "job_scope": {}},
    {"company_name": "Accenture", "job_scope": {}},
    {"company_name": "Hcl America", "job_scope": {}},
    {"company_name": "Wipro", "job_scope": {}},
    {"company_name": "Tech Mahindra", "job_scope": {}},
    {"company_name": "Larsen & Toubro Infotech", "job_scope": {}},
    {"company_name": "Facebook", "job_scope": {}},
    {"company_name": "WalMart Associates", "job_scope": {}},
    {"company_name": "L&T Technology Services", "job_scope": {}},
    {"company_name": "Syntel", "job_scope": {}},
    {"company_name": "Stripe", "job_scope": {}},
    {"company_name": "Salesforce", "job_scope": {}},
    {"company_name": "Amazon Web Services", "job_scope": {}},
    {"company_name": "Apple", "job_scope": {}},
    {"company_name": "Intel", "job_scope": {}},
    {"company_name": "Compunnel Software Group", "job_scope": {}},
    {"company_name": "Goldman Sachs", "job_scope": {}},
    {"company_name": "Erp Analysts", "job_scope": {}},
    {"company_name": "Adobe", "job_scope": {}},
    {"company_name": "Zs Associates", "job_scope": {}},
    {"company_name": "T-Mobile", "job_scope": {}},
    {"company_name": "Sap America", "job_scope": {}},
    {"company_name": "The Mathworks", "job_scope": {}},
    {"company_name": "Prokarma", "job_scope": {}},
    {"company_name": "Expedia", "job_scope": {}},
    {"company_name": "Persistent Systems", "job_scope": {}},
    {"company_name": "Natsoft", "job_scope": {}},
    {"company_name": "Iris Software", "job_scope": {}},
    {"company_name": "Micron Technology", "job_scope": {}},
    {"company_name": "Infoshare Systems", "job_scope": {}},
    {"company_name": "American Express Travel Related Services", "job_scope": {}},
    {"company_name": "Optum Services", "job_scope": {}},
    {"company_name": "The Boston Consulting Group", "job_scope": {}},
    {"company_name": "Ciber Global", "job_scope": {}},
    {"company_name": "Bloomberg", "job_scope": {}},
    {"company_name": "Stanford University", "job_scope": {}},
    {"company_name": "Juniper Networks", "job_scope": {}},
    {"company_name": "Qualcomm Technologies", "job_scope": {}},
    {"company_name": "Randstad Technologies", "job_scope": {}},
    {"company_name": "Pricewaterhousecoopers Advisory Services", "job_scope": {}},
    {"company_name": "Mphasis", "job_scope": {}},
    {"company_name": "Uber", "job_scope": {}},
    {"company_name": "Virtusa", "job_scope": {}},
    {"company_name": "LinkedIn", "job_scope": {}},
    {"company_name": "Mastech Digital Technologies", "job_scope": {}},
    {"company_name": "Capital One Services", "job_scope": {}},
    {"company_name": "Mindtree", "job_scope": {}},
    {"company_name": "Hexaware Technologies", "job_scope": {}},
    {"company_name": "VM Ware", "job_scope": {}},
    {"company_name": "Synechron", "job_scope": {}},
    {"company_name": "Paypal", "job_scope": {}},
    {"company_name": "Oracle", "job_scope": {}},
    {"company_name": "Ust Global", "job_scope": {}},
    {"company_name": "Tesla", "job_scope": {}},
    {"company_name": "Bank Of America", "job_scope": {}},
    {"company_name": "Kpmg", "job_scope": {}},
    {"company_name": "Populus Group", "job_scope": {}},
    {"company_name": "Cisco Systems", "job_scope": {}},
    {"company_name": "Citicorp Credit Services", "job_scope": {}},
    {"company_name": "Cummins", "job_scope": {}},
    {"company_name": "Hcl Global Systems", "job_scope": {}},
    {"company_name": "Marlabs", "job_scope": {}},
    {"company_name": "Cerner", "job_scope": {}},
    {"company_name": "Comcast Cable Communications", "job_scope": {}},
    {"company_name": "V-Soft Consulting Group", "job_scope": {}},
    {"company_name": "Avco Consulting", "job_scope": {}},
    {"company_name": "Ebay", "job_scope": {}},
    {"company_name": "Kforce", "job_scope": {}},
    {"company_name": "Citiustech", "job_scope": {}},
    {"company_name": "Quest Global Services-NA", "job_scope": {}},
    {"company_name": "Htc Global Services", "job_scope": {}},
    {"company_name": "Collaborate Solutions", "job_scope": {}},
    {"company_name": "Morgan Stanley Services Group", "job_scope": {}},
    {"company_name": "Barclays Services", "job_scope": {}},
    {"company_name": "Dell", "job_scope": {}},
    {"company_name": "Anthem", "job_scope": {}},
    {"company_name": "Blackrock Financial Management", "job_scope": {}},
    {"company_name": "Intuit", "job_scope": {}},
    {"company_name": "Ntt Data Services", "job_scope": {}},
    {"company_name": "Databricks", "job_scope": {}},
    {"company_name": "Roblox", "job_scope": {}},
    {"company_name": "Coinbase", "job_scope": {}}
]