#file will have the list of dictionaries for each company
#will be used to populate the database once all data is collected

companies = [
    {"company_name": "Cognizant Technology Solutions", "job_scope": {}},
    {"company_name": "Infosys", "job_scope": {}},
    {"company_name": "Tata Consultancy Services", "job_scope": {}},
    {"company_name": "Google", "job_scope": {}},
    {"company_name": "Ernst & Young", "job_scope": {}},
    {"company_name": "Capgemini", "job_scope": {}},
    {"company_name": "Deloitte & Touche", "job_scope": {}},
    {"company_name": "Amazon", "job_scope": {}},
    {"company_name": "IBM", "job_scope": {}},
    {"company_name": "Microsoft", "job_scope": {}},
    {"company_name": "Accenture", "job_scope": {}},
    {"company_name": "Hcl America", "job_scope": {}},
    {"company_name": "Wipro", "job_scope": {}},
    {"company_name": "Tech Mahindra", "job_scope": {}},
    {"company_name": "Larsen & Toubro Infotech", "job_scope": {}},
    {"company_name": "Facebook", "job_scope": {}},
    {"company_name": "WalMart Associates", "job_scope": {}},
    {"company_name": "L&T Technology Services", "job_scope": {}},
    {"company_name": "Syntel", "job_scope": {}},
    {"company_name": "", "job_scope": {}},
    {"company_name": "", "job_scope": {}},
    {"company_name": "", "job_scope": {}},
    {"company_name": "", "job_scope": {}},
    {"company_name": "", "job_scope": {}},
    {"company_name": "", "job_scope": {}},
    {"company_name": "", "job_scope": {}},
    {"company_name": "", "job_scope": {}},
    {"company_name": "", "job_scope": {}},
    {"company_name": "", "job_scope": {}},
    {"company_name": "", "job_scope": {}},
    {"company_name": "", "job_scope": {}},
    {"company_name": "", "job_scope": {}},
    {"company_name": "", "job_scope": {}},
    {"company_name": "", "job_scope": {}},
    {"company_name": "", "job_scope": {}},
    {"company_name": "", "job_scope": {}},
    {"company_name": "", "job_scope": {}},
    {"company_name": "", "job_scope": {}},
    {"company_name": "", "job_scope": {}},
    {"company_name": "", "job_scope": {}},
    {"company_name": "", "job_scope": {}},
    {"company_name": "", "job_scope": {}},
    {"company_name": "", "job_scope": {}},
    {"company_name": "", "job_scope": {}},
    {"company_name": "", "job_scope": {}},
    {"company_name": "", "job_scope": {}},
    {"company_name": "", "job_scope": {}},
    {"company_name": "", "job_scope": {}},
    {"company_name": "", "job_scope": {}},
    {"company_name": "", "job_scope": {}},
    {"company_name": "", "job_scope": {}},
    {"company_name": "", "job_scope": {}},
    {"company_name": "", "job_scope": {}},
    {"company_name": "", "job_scope": {}},
    {"company_name": "", "job_scope": {}},
    {"company_name": "", "job_scope": {}},
    {"company_name": "", "job_scope": {}},
    {"company_name": "", "job_scope": {}},
    {"company_name": "", "job_scope": {}},
    {"company_name": "", "job_scope": {}},
    {"company_name": "", "job_scope": {}},
    {"company_name": "", "job_scope": {}},
    {"company_name": "", "job_scope": {}},
    {"company_name": "", "job_scope": {}},
    {"company_name": "", "job_scope": {}},
    {"company_name": "", "job_scope": {}},
    {"company_name": "", "job_scope": {}},
    {"company_name": "", "job_scope": {}},
    {"company_name": "", "job_scope": {}},
    {"company_name": "", "job_scope": {}},
    {"company_name": "", "job_scope": {}},
    {"company_name": "", "job_scope": {}},
    {"company_name": "", "job_scope": {}},
    {"company_name": "", "job_scope": {}},
    {"company_name": "", "job_scope": {}},
    {"company_name": "", "job_scope": {}},
    {"company_name": "", "job_scope": {}},
    {"company_name": "", "job_scope": {}},
    {"company_name": "", "job_scope": {}},
    {"company_name": "", "job_scope": {}},
    {"company_name": "", "job_scope": {}},
    {"company_name": "", "job_scope": {}},
    {"company_name": "", "job_scope": {}},
    {"company_name": "", "job_scope": {}},
    {"company_name": "", "job_scope": {}},
    {"company_name": "", "job_scope": {}},
    {"company_name": "", "job_scope": {}},
    {"company_name": "", "job_scope": {}},
    {"company_name": "", "job_scope": {}},
    {"company_name": "", "job_scope": {}},
    {"company_name": "", "job_scope": {}},
    {"company_name": "", "job_scope": {}}
]